### PR TITLE
Classiq HW1 and HW2 submission

### PR DESCRIPTION
**Pull request by NoahNzeki**
Submission of QWorld_Classiq first and second assignment.

### CODE REVIEW

**Comment by Nadav138** [comment]
Hello @NoahNzeki !
Well done! Seems good. You do have another PR with HW3 as well as few unintended changes. You might might add HW3 here (update the branch before, to avoid conflicts). You might also submit HW3 in deferent branch.
For now I keep both of your PRs open, but you should note those issue before I can approve it🙏🏽

**Comment by NoahNzeki** [comment]
> Hello @NoahNzeki ! Well done! Seems good. You do have another PR with HW3 as well as few unintended changes. You might might add HW3 here (update the branch before, to avoid conflicts). You might also submit HW3 in deferent branch. For now I keep both of your PRs open, but you should note those issue before I can approve it🙏🏽

Hello @Nadav138 ! Noted and corrected. Thanks.

**Comment by NoahNzeki** [comment]
> Hello @NoahNzeki ! Well done! Seems good. You do have another PR with HW3 as well as few unintended changes. You might might add HW3 here (update the branch before, to avoid conflicts). You might also submit HW3 in deferent branch. For now I keep both of your PRs open, but you should note those issue before I can approve it🙏🏽

Hello @Nadav138 ! Noted and corrected. Thanks.

**Comment by NoahNzeki** [comment]
> Hello @NoahNzeki ! Well done! Seems good. You do have another PR with HW3 as well as few unintended changes. You might might add HW3 here (update the branch before, to avoid conflicts). You might also submit HW3 in deferent branch. For now I keep both of your PRs open, but you should note those issue before I can approve it🙏🏽

Hello @Nadav138 ! Noted and corrected. Thanks.

**Review by Nadav138 — APPROVED** [review]

**Pull request merged**
