### PR TITLE
Womanium Final Assignment - Hao Mack Yang Lee

### PR DESCRIPTION
**Pull request by mulliganaceous**
### PR Description

This is a demo of the quantum walk for various node configurations.

### Some notes

- [x] Please make sure that you placed the files in an appropriate folder
- [x] And that the files have indicative names.

- [x] Please note that Classiq runs automatic code linting, which may minorly alter some files.
- [x] If you're familiar with `pre-commit`, you may run `pre-commit install`, and then at each commit, your files will be altered in a similar way

### CODE REVIEW

**Comment by mulliganaceous** [comment]
Submission submitted at 23:58 ET

**Comment by amir-naveh** [comment]
Hi @mulliganaceous  - we've closed the acceptance of further PR's for the womanium course, so I am closing this PR. This will not hurt your grade in the course. Thank you. @Nadav138 , @EdenSchirmanClassiq FYI

**Comment by mulliganaceous** [comment]
Hi @amir-naveh, they have made a last-day fix for the submissions. I will resubmit the pull request at the close of this day.

**Comment by NadavClassiq** [comment]
Well done @mulliganaceous!
Score: 8/10.

**Comment by mulliganaceous** [comment]
@NadavClassiq Thanks. Is this the original, since I resubmitted it again a few days after the deadline (namely the Sunday).
I am also learning how to improve this submission to make it a 9 or a 10. My partner @PhiloMathysicist, notably, got a 9. It seems the great majority of passing submissions are 8s, with few 9s or 10s.

Here is a fun fact: We both won the Fraunhofer project as a team and individuals.

**Comment by NadavClassiq** [comment]
Hello @mulliganaceous :)
I am unsure if I get the question. Do you ask me if this is the original submission? If so, I am unsure as I checked many of them, and I don't remember each one in detail.

We generally accept resubmissions after the deadline, but both you and @PhiloMathysicist received great grades. Well done!

**Comment by mulliganaceous** [comment]
PR #449 is the original. PR #456 is the resubmission, containing the circuit diagram. I am looking for next steps, especially for getting a 10/10.

**Comment by NadavClassiq** [comment]
#449 was graded as it was submitted on time. #456 wasn't as it was submitted after the deadline. 
I hope It's all clear now.

**Comment by NadavClassiq** [comment]
Hi @mulliganaceous, grades 8/10 were given to good and correct assignments, while 9/10 and 10/10 were given to more detailed solutions with extra elaboration, demonstration of knowledge, special visualization, etc.

**Pull request closed without merging**
