### PR TITLE
Rithik_Rai_hw4.ipynb

### PR DESCRIPTION
**Pull request by iarithik**
Uploaded assignment submission

### Some notes

- [ ] Please make sure that you placed the files in an appropriate folder
- [ ] And that the files have indicative names.

- [ ] Please note that Classiq runs automatic code linting, which may minorly alter some files.
  - [ ] If you're familiar with `pre-commit`, you may run `pre-commit install`, and then at each commit, your files will be altered in a similar way

### CODE REVIEW

**Comment by amir-naveh** [comment]
Hi @iarithik - we've closed the acceptance of further PR's for the womanium course, so I am closing this PR. This will not hurt your grade in the course. Thank you. @Nadav138 , @EdenSchirmanClassiq FYI

**Comment by NadavClassiq** [comment]
Hello @iarithik! The deadline passed on 24.8; we don't check late submissions.
Well done for the effort!

**Comment by iarithik** [comment]
Hello @NadavClassiq, I submitted it well within the deadline. Because there was some issue with classiq github, womanium had extended the deadline to 25th August ET. So, please recheck the deadline. And let me know, so that if there is some issue I may approach womanium for the same.

**Comment by NadavClassiq** [comment]
This commit is from the 26 Aug, meaning after the deadline.
If Womanium accepts this late submission, the Score will be 8/10.

**Pull request closed without merging**
