### PR TITLE
Hao Mack Yang Resubmission 

### PR DESCRIPTION
**Pull request by mulliganaceous**
### PR Description

Resubmission. Will run again later at the close of today. Contains a graph of all the shots.

### Some notes

- [ ] Please make sure that you placed the files in an appropriate folder
- [ ] And that the files have indicative names.

- [ ] Please note that Classiq runs automatic code linting, which may minorly alter some files.
 - [ ] If you're familiar with `pre-commit`, you may run `pre-commit install`, and then at each commit, your files will be altered in a similar way

### CODE REVIEW

**Comment by amir-naveh** [comment]
Hi @mulliganaceous - we've closed the acceptance of further PR's for the womanium course, so I am closing this PR. This will not hurt your grade in the course. Thank you. @Nadav138 , @EdenSchirmanClassiq FYI

**Comment by mulliganaceous** [comment]
Circuit 16-1

At around 03:26 EDT today, the Classiq team fixed the 396930 bug.

**Comment by NadavClassiq** [comment]
Hello @RamAIbot! The deadline passed on 24.8; we don't check late submissions.
Well done for the effort!

**Comment by mulliganaceous** [comment]
> Hello @RamAIbot! The deadline passed on 24.8; we don't check late submissions. Well done for the effort!

I already submitted everything.

**Comment by NadavClassiq** [comment]
Hi @mulliganaceous, You did submit everything, but this PR opened after the deadline and due to that wasn't graded.
Best luck!

**Pull request closed without merging**
