### PR TITLE
HW-1 Submission

### PR DESCRIPTION
**Pull request by Bill-Wisotsky**
Submission of HW-1 for Bill Wisotsky

### CODE REVIEW

**Comment by EdenSchirmanClassiq** [comment]
@Bill-Wisotsky Thanks for opening this PR. Note that there are many .DS_store files in your commit. They should not be there. Please change this PR such that it contains only the files with the HW

**Comment by Bill-Wisotsky** [comment]
Trying this again. There is only on file in the for each of the homework. Not sure what you mean by .DS_store files

**Comment by Bill-Wisotsky** [comment]
HW1

**Comment by Bill-Wisotsky** [comment]
mnmnm

**Pull request closed without merging**
