### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mohammadalimrg1997**
the assignment for womanium 6.12

### Some notes

- [x] Please make sure that you placed the files in an appropriate folder
- [x] And that the files have indicative names.

- [x] Please note that Classiq runs automatic code linting, which may minorly alter some files.
  - [x] If you're familiar with `pre-commit`, you may run `pre-commit install`, and then at each commit, your files will be altered in a similar way

### CODE REVIEW

**Comment by amir-naveh** [comment]
Hi @mohammadalimrg1997  - we've closed the acceptance of further PR's for the womanium course, so I am closing this PR. This will not hurt your grade in the course. Thank you

**Comment by mohammadalimrg1997** [comment]
I have this problem.mine wasn't graded in the first instance so I did
repull it.can you check if it is graded?

**Comment by mohammadalimrg1997** [comment]
I would highly appreciate it

**Comment by NadavClassiq** [comment]
Hello @mohammadalimrg1997!
Well done, the score is 6/10.
Your conditions are not as instructed (open vs closed). I recommend checking the relevant session recording and instructions again.

**Comment by mohammadalimrg1997** [comment]
Thank you, I will do that.

**Pull request closed without merging**
