### PR TITLE
Womanium Final Assignment - Martyna Czuba

### PR DESCRIPTION
**Pull request by Martyna94**
This pull request contains the final submission for the Womanium assignment by Martyna Czuba, titled "Martyna_Czuba_hw4.ipynb". The assignment is located in the folder community/womanium/assignments

### CODE REVIEW

**Comment by amir-naveh** [comment]
Hi @Martyna94  - we've closed the acceptance of further PR's for the womanium course, so I am closing this PR. This will not hurt your grade in the course. Thank you. @Nadav138 , @EdenSchirmanClassiq FYI

**Comment by Martyna94** [comment]
Hi @amir-naveh. We got the message and on the Canvas platform it  says that resubmitting is available until August 22. Why, then, has this PR been closed?

**Comment by EdenSchirmanClassiq** [comment]
Hi @Martyna94 , indeed you can resubmit and we will grade this PR, it is just it won't be merged to the library

**Comment by Martyna94** [comment]
@EdenSchirmanClassiq, thanks.:)

**Comment by NadavClassiq** [comment]
Hello @Martyna94!
Well done, the score is 8/10 :)

**Pull request closed without merging**
